apiVersion: v1
kind: Service
metadata:
  annotations:
    description: The web server's http port.
  labels:
    application: hibbus
    template: eap64-basic-s2i
    xpaas: 1.1.0
  name: hibbus-ejb
spec:
  ports:
  - port: 4447
    protocol: TCP
    targetPort: 4447
  selector:
    deploymentConfig: hibbus
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}